name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}/settings.xml # Path to the settings.xml file

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B -s .github/maven-settings.xml package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -s .github/maven-settings.xml deploy
      env:
        GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the GitHub Packages token

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: docker.pkg.github.com/${{ github.repository }}/my-image:latest