name: Echo Secrets

on:
  workflow_dispatch:

env:
  DEV_SECRET: ${{ secrets.DEV_SECRET }}
  ORG_SECRET: ${{ secrets.ORG_SECRET }}

jobs:
  echo-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Secret
        run: |
          echo "DEV_SECRET: ${{ secrets.DEV_SECRET }}"
          echo "ORG_SECRET: ${{ secrets.ORG_SECRET }}"
          echo "env DEV_SECRET: ${{ env.DEV_SECRET }}"
          echo "env ORG_SECRET: ${{ env.ORG_SECRET }}"

      # - name: call common.yml
      #   uses: konamugi-organization/wf-test-common/.github/workflow/common.yml@main
      #   with:
      #     secrets:
      #       dev_secret: ${{ secrets.DEV_SECRET }}
      #       common_secret: ${{ secrets.ORG_SECRET }}
